SET FOREIGN_KEY_CHECKS = 0; 

TRUNCATE TABLE Category;
TRUNCATE TABLE Brand;
TRUNCATE TABLE Product;
TRUNCATE TABLE Person;
TRUNCATE TABLE `Account`;
TRUNCATE TABLE Bill;
TRUNCATE TABLE Bill_Product;

SET FOREIGN_KEY_CHECKS = 1; 